CREATE TABLE `str_id` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`str` VARCHAR(16) NOT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `str` (`str`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `market_data` (
	`symbol_id` INT(11) NOT NULL,
	`time` DATETIME NOT NULL,
	`open` DOUBLE NOT NULL,
	`high` DOUBLE NOT NULL,
	`low` DOUBLE NOT NULL,
	`close` DOUBLE NOT NULL,
	`volume` DOUBLE NOT NULL,
	`updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
	PRIMARY KEY (`symbol_id`, `time`) USING BTREE,
	CONSTRAINT `market_data_ibfk_1` FOREIGN KEY (`symbol_id`) REFERENCES `str_id` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;



